### ISSUE TITLE
[sprint 3] add general search functionality to v2

### ISSUE THREAD

**Issue by nikzei** [18F/privacy-tools#30]
Currently, a user can run key word searches for the three categories of information that the card-based layout presents: SORNs, PIAs, and PII categories. 

We want a user to be able to run a general key word search against all these three fields (so that if they search for "payroll," the results will include all SORNs, PIAs and PIIs that contain this word).

Acceptance Criteria:
- [x] our card-based prototype has a "general search" field
- [x] we make an intentional design decision to clearly delineate this general search from the other more specific field searches (cc @igorkorenfeld) 
- [x] keyword searches entered into this field produce results from SORNs, PIAs, and PII types
- [x] filters (or lack of them) is clearly indicated on page with search results (currently we do this for search results on the top lefthand corner of the card layout)
- [x] number of results are clearly indicated on the page with search results (currently we do this for search results on the top righthand corner of the card layout)
     - [x] decide how to display number of search results. For system searches, we say results are x out of 85. When we conduct a general search, do we want to say the total = # systems + # of PIAs + # of SORNs + # of PII categories? Probably not - that might produce a huge number that isn't particularly meaningful. Maybe we just say search results without listing the total? We'll have to make that decision.
- [x] I think the search keyterm should be highlighted in the PII section because it makes it clear why a certain result was returned.
- [x] Submitting a search should also be performed when the user presses "Enter." I believe that's a standard pattern and requiring a button click isn't best practice.
- [x] Search styling needs to be adjusted so it that the button is the same height as the search bar, and better matches the USWDS example.
- [x] Pass highlight integration test (when search field is empty but not submitted)

**Comment by igorkorenfeld** [comment]
I've worked on mockups for general search. I suggest we keep the filters sidebar present and allow filtering to happen either before or after the search, if that's feasible from an engineering perspective. Filtering before a search would work as it does in our prototype now – narrowing down the list of all record to those that match the filters for each field. 

When a user searches, the general search tries to match any of the fields for the keyword. It shows records that match that keyword and highlights it in the PII field (perhaps it makes sense to also highlight in the other fields, beside the name?). The user can then narrow down the results further by applying filters, meaning the result has to match both the search keyword and the filter for the specific field. 

I think the results count should now reflect the number of records that match the keyword search. So if there are 2 records that match a keyword search for "number", the counter would say _Showing **2** of **2** results for "number"_. When a user filters the first number would change to reflect how many records remain after the filter is applied. So in this case _Showing **1** of **2** results for "number"_. In the case where a filter is applied without a general search keyword, the base number is the total number of records as it is now, since that is the equivalent of the keyword being `all records`. 

**Search for keyword**
![PrvOps_Search_Keyword](https://user-images.githubusercontent.com/52677065/75904263-e0aad080-5e10-11ea-8af6-2c27ec1004a3.png)

**Apply a filter after searching**
![PrvOps_Search_Keyword_Filtered](https://user-images.githubusercontent.com/52677065/75904369-1780e680-5e11-11ea-9a6c-7c85227537c7.png)

**Apply a filter after searching, with no matches**
![PrvOps_Search_Keyword_Fitlered-None](https://user-images.githubusercontent.com/52677065/75905334-afcb9b00-5e12-11ea-97a3-8cef0fb81d06.png)


**Search for keyword with no matches**
![PrvOps_Search_Keyword_None](https://user-images.githubusercontent.com/52677065/75905348-b3f7b880-5e12-11ea-875b-39e8062e4b32.png)

**Comment by ondrae** [comment]
Thanks Igor, we can get started now. We'll figure out how to build these features.

On first look, it seems super complicated for users. Four search bars with overlapping effects, checkboxes with slightly different effects, pill, highlights, counts, and pagination.

Is all that needed? Is it because our users are power user lawyers who want to be able to do lots of different analysis in our tool? Is there a way for us to do the hard work to make it simpler?

**Comment by igorkorenfeld** [comment]
I think that's a fair point. Certain things we've heard are definitely useful, the keyword highlighting and count in particular come to mind. But maybe we can try it without some of the other parts. 

If we have general search, then we might not need the SORN-ID filter. My guess is that's something they could search for using the general search and the results will still be relevant. 

Similarly, it didn't seem like the Quick Filters were something that Marcela was looking at. Clicking the box isn't much faster than typing in the filter, and the fact that the checking action is opposite to the type filters might be a little confusing. So I think we can drop those for now as well. 

Let me know if you have any other suggestions, and I can update the mockup to reflect a simplified version.

**Comment by igorkorenfeld** [comment]
Simplified down, without the SORN-ID filter or the quick filters:

![PrvOps_Search_Keyword_Simplified](https://user-images.githubusercontent.com/52677065/75919385-73586900-5e2b-11ea-9539-b0d4188cd131.png)

**Comment by igorkorenfeld** [comment]
It's looking really good a few things I notice:
- I think the search keyterm should be highlighted in the PII section because it makes it clear why a certain result was returned.
- Submitting a search should also be performed when the user presses "Enter." I believe that's a standard pattern and requiring a button click isn't best practice. 
- Search styling needs to be adjusted so it that the button is the same height as the search bar, and better matches the USWDS example. 

In the future I would like to add  the option to clear out filters from the active filter area. I think we can put this off for now, but that will make for a smoother experience as well, especially now that the filters overlap with the general search.

**Comment by igorkorenfeld** [comment]
This is almost good to go, it is currently failing one of the integration tests, "the card page general search and filters at the same time when removing filters and searches highlights correctly, when search field is empty but not submitted"

**Comment by ondrae** [comment]
@igorkorenfeld I got those last tests passing, about to make a PR.

I've never seen `onsubmit="return false"`. Nice. I usually have to do a `event.preventDefault();` inside a listener function. Thanks for the simpler tip.

**Comment by igorkorenfeld** [comment]
Great! 

Yeah, my first time using that. I wasn't sure if it's best practice, but it worked!
